// AUTO-GENERATED by Seefar from the live Supabase schema — do not edit by hand.
// Every Supabase query in this app is type-checked against the fields below.
// If the schema changes, re-run the Supabase integration to refresh this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      addresses: {
        Row: {
          city: string | null
          created_at: string | null
          id: string
          isDefault: boolean | null
          label: string | null
          latitude: number | null
          longitude: number | null
          street: string | null
          updated_at: string | null
          userId: string
          zipCode: string | null
        }
        Insert: {
          city?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          street?: string | null
          updated_at?: string | null
          userId: string
          zipCode?: string | null
        }
        Update: {
          city?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          label?: string | null
          latitude?: number | null
          longitude?: number | null
          street?: string | null
          updated_at?: string | null
          userId?: string
          zipCode?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "addresses_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      deliveryPartners: {
        Row: {
          avatar: string | null
          created_at: string | null
          id: string
          latitude: number | null
          longitude: number | null
          name: string
          phone: string | null
          rating: number | null
          updated_at: string | null
          vehiclePlate: string | null
          vehicleType: string | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
          phone?: string | null
          rating?: number | null
          updated_at?: string | null
          vehiclePlate?: string | null
          vehicleType?: string | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
          phone?: string | null
          rating?: number | null
          updated_at?: string | null
          vehiclePlate?: string | null
          vehicleType?: string | null
        }
        Relationships: []
      }
      menuItems: {
        Row: {
          calories: number | null
          category: string | null
          created_at: string | null
          description: string | null
          id: string
          imageUrl: string | null
          isAvailable: boolean | null
          isGlutenFree: boolean | null
          isVegan: boolean | null
          isVegetarian: boolean | null
          name: string
          price: number
          restaurantId: string
          updated_at: string | null
        }
        Insert: {
          calories?: number | null
          category?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          imageUrl?: string | null
          isAvailable?: boolean | null
          isGlutenFree?: boolean | null
          isVegan?: boolean | null
          isVegetarian?: boolean | null
          name: string
          price: number
          restaurantId: string
          updated_at?: string | null
        }
        Update: {
          calories?: number | null
          category?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          imageUrl?: string | null
          isAvailable?: boolean | null
          isGlutenFree?: boolean | null
          isVegan?: boolean | null
          isVegetarian?: boolean | null
          name?: string
          price?: number
          restaurantId?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "menuItems_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string | null
          id: string
          isRead: boolean | null
          orderId: string | null
          title: string | null
          type: string | null
          userId: string
        }
        Insert: {
          body?: string | null
          created_at?: string | null
          id?: string
          isRead?: boolean | null
          orderId?: string | null
          title?: string | null
          type?: string | null
          userId: string
        }
        Update: {
          body?: string | null
          created_at?: string | null
          id?: string
          isRead?: boolean | null
          orderId?: string | null
          title?: string | null
          type?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      orderItemCustomizations: {
        Row: {
          created_at: string | null
          groupId: string | null
          groupName: string | null
          id: string
          optionId: string | null
          optionName: string | null
          orderItemId: string
          price: number | null
        }
        Insert: {
          created_at?: string | null
          groupId?: string | null
          groupName?: string | null
          id?: string
          optionId?: string | null
          optionName?: string | null
          orderItemId: string
          price?: number | null
        }
        Update: {
          created_at?: string | null
          groupId?: string | null
          groupName?: string | null
          id?: string
          optionId?: string | null
          optionName?: string | null
          orderItemId?: string
          price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "orderItemCustomizations_orderItemId_fkey"
            columns: ["orderItemId"]
            isOneToOne: false
            referencedRelation: "orderItems"
            referencedColumns: ["id"]
          },
        ]
      }
      orderItems: {
        Row: {
          created_at: string | null
          id: string
          menuItemId: string
          orderId: string
          quantity: number
          specialInstructions: string | null
          totalPrice: number
        }
        Insert: {
          created_at?: string | null
          id?: string
          menuItemId: string
          orderId: string
          quantity: number
          specialInstructions?: string | null
          totalPrice: number
        }
        Update: {
          created_at?: string | null
          id?: string
          menuItemId?: string
          orderId?: string
          quantity?: number
          specialInstructions?: string | null
          totalPrice?: number
        }
        Relationships: [
          {
            foreignKeyName: "orderItems_menuItemId_fkey"
            columns: ["menuItemId"]
            isOneToOne: false
            referencedRelation: "menuItems"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orderItems_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          actualDeliveryTime: string | null
          created_at: string | null
          deliveryAddressId: string | null
          deliveryFee: number | null
          deliveryPartnerId: string | null
          discount: number | null
          estimatedDeliveryTime: string | null
          id: string
          paymentMethodId: string | null
          promoCode: string | null
          rating: number | null
          restaurantId: string
          review: string | null
          status: string | null
          subtotal: number | null
          tax: number | null
          totalPrice: number
          updated_at: string | null
          userId: string
        }
        Insert: {
          actualDeliveryTime?: string | null
          created_at?: string | null
          deliveryAddressId?: string | null
          deliveryFee?: number | null
          deliveryPartnerId?: string | null
          discount?: number | null
          estimatedDeliveryTime?: string | null
          id?: string
          paymentMethodId?: string | null
          promoCode?: string | null
          rating?: number | null
          restaurantId: string
          review?: string | null
          status?: string | null
          subtotal?: number | null
          tax?: number | null
          totalPrice: number
          updated_at?: string | null
          userId: string
        }
        Update: {
          actualDeliveryTime?: string | null
          created_at?: string | null
          deliveryAddressId?: string | null
          deliveryFee?: number | null
          deliveryPartnerId?: string | null
          discount?: number | null
          estimatedDeliveryTime?: string | null
          id?: string
          paymentMethodId?: string | null
          promoCode?: string | null
          rating?: number | null
          restaurantId?: string
          review?: string | null
          status?: string | null
          subtotal?: number | null
          tax?: number | null
          totalPrice?: number
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_deliveryAddressId_fkey"
            columns: ["deliveryAddressId"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_paymentMethodId_fkey"
            columns: ["paymentMethodId"]
            isOneToOne: false
            referencedRelation: "paymentMethods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      orderStatusHistory: {
        Row: {
          created_at: string | null
          id: string
          message: string | null
          orderId: string
          status: string
          timestamp: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          message?: string | null
          orderId: string
          status: string
          timestamp?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          message?: string | null
          orderId?: string
          status?: string
          timestamp?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "orderStatusHistory_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
        ]
      }
      paymentMethods: {
        Row: {
          cardBrand: string | null
          cardExpiry: string | null
          cardLast4: string | null
          created_at: string | null
          id: string
          isDefault: boolean | null
          type: string | null
          updated_at: string | null
          userId: string
        }
        Insert: {
          cardBrand?: string | null
          cardExpiry?: string | null
          cardLast4?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          type?: string | null
          updated_at?: string | null
          userId: string
        }
        Update: {
          cardBrand?: string | null
          cardExpiry?: string | null
          cardLast4?: string | null
          created_at?: string | null
          id?: string
          isDefault?: boolean | null
          type?: string | null
          updated_at?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "paymentMethods_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      promoCodes: {
        Row: {
          code: string
          created_at: string | null
          discountType: string | null
          discountValue: number
          expiresAt: string | null
          id: string
          isValid: boolean | null
          maxDiscount: number | null
          minOrderAmount: number | null
          updated_at: string | null
        }
        Insert: {
          code: string
          created_at?: string | null
          discountType?: string | null
          discountValue: number
          expiresAt?: string | null
          id?: string
          isValid?: boolean | null
          maxDiscount?: number | null
          minOrderAmount?: number | null
          updated_at?: string | null
        }
        Update: {
          code?: string
          created_at?: string | null
          discountType?: string | null
          discountValue?: number
          expiresAt?: string | null
          id?: string
          isValid?: boolean | null
          maxDiscount?: number | null
          minOrderAmount?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      restaurants: {
        Row: {
          address: string | null
          created_at: string | null
          cuisine: string[] | null
          deliveryFee: number | null
          deliveryTime: string | null
          distance: string | null
          id: string
          imageUrl: string | null
          isOpen: boolean | null
          latitude: number | null
          longitude: number | null
          minOrder: number | null
          name: string
          priceRange: string | null
          rating: number | null
          reviewCount: number | null
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          cuisine?: string[] | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          distance?: string | null
          id?: string
          imageUrl?: string | null
          isOpen?: boolean | null
          latitude?: number | null
          longitude?: number | null
          minOrder?: number | null
          name: string
          priceRange?: string | null
          rating?: number | null
          reviewCount?: number | null
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          cuisine?: string[] | null
          deliveryFee?: number | null
          deliveryTime?: string | null
          distance?: string | null
          id?: string
          imageUrl?: string | null
          isOpen?: boolean | null
          latitude?: number | null
          longitude?: number | null
          minOrder?: number | null
          name?: string
          priceRange?: string | null
          rating?: number | null
          reviewCount?: number | null
          updated_at?: string | null
        }
        Relationships: []
      }
      reviews: {
        Row: {
          created_at: string | null
          id: string
          imageUrls: string[] | null
          orderId: string | null
          rating: number
          restaurantId: string
          text: string | null
          updated_at: string | null
          userAvatar: string | null
          userId: string
          userName: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          imageUrls?: string[] | null
          orderId?: string | null
          rating: number
          restaurantId: string
          text?: string | null
          updated_at?: string | null
          userAvatar?: string | null
          userId: string
          userName?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          imageUrls?: string[] | null
          orderId?: string | null
          rating?: number
          restaurantId?: string
          text?: string | null
          updated_at?: string | null
          userAvatar?: string | null
          userId?: string
          userName?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_orderId_fkey"
            columns: ["orderId"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      seefar_metadata: {
        Row: {
          app_id: string
          app_name: string
          created_at: string | null
          id: string
          seefar_origin: boolean | null
        }
        Insert: {
          app_id: string
          app_name: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Update: {
          app_id?: string
          app_name?: string
          created_at?: string | null
          id?: string
          seefar_origin?: boolean | null
        }
        Relationships: []
      }
      userFavorites: {
        Row: {
          created_at: string | null
          id: string
          restaurantId: string
          userId: string
        }
        Insert: {
          created_at?: string | null
          id?: string
          restaurantId: string
          userId: string
        }
        Update: {
          created_at?: string | null
          id?: string
          restaurantId?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "userFavorites_restaurantId_fkey"
            columns: ["restaurantId"]
            isOneToOne: false
            referencedRelation: "restaurants"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "userFavorites_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          avatar: string | null
          created_at: string | null
          defaultAddressId: string | null
          email: string | null
          id: string
          name: string | null
          phone: string | null
          referralCode: string | null
          updated_at: string | null
          walletBalance: number | null
        }
        Insert: {
          avatar?: string | null
          created_at?: string | null
          defaultAddressId?: string | null
          email?: string | null
          id: string
          name?: string | null
          phone?: string | null
          referralCode?: string | null
          updated_at?: string | null
          walletBalance?: number | null
        }
        Update: {
          avatar?: string | null
          created_at?: string | null
          defaultAddressId?: string | null
          email?: string | null
          id?: string
          name?: string | null
          phone?: string | null
          referralCode?: string | null
          updated_at?: string | null
          walletBalance?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
